[workspace]

members = ["rmapi", "rmclient"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "NCSA"
authors = ["David ter Kuile"]
homepage = "https://github.com/doterkuile/rmapi-rs"
repository = "https://github.com/doterkuile/rmapi-rs"
